title: WebApp Docs
email: woojiahao@nushackers.org
description: >- # this means to ignore newlines until "baseurl:"
  Documentation hub for the Hack&Roll website.
baseurl: ""
url: ""

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

enable_copy_code_button: true

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow